### ISSUE TITLE
server will not run  running host authserver.mojang.com works OK

### ISSUE THREAD

**Issue by gzcwnk** [AllTheMods/atm9nf#45]
trying to start a server on debian12 and I get,
steven@minecraft01:~/minecraft/atm9nofrills/Server-Files-0.1.8$ sh startserver.sh
Forge not installed, installing now.
Running Forge installer.
JVM info: Debian - 17.0.10 - 17.0.10+7-Debian-1deb12u1
java.net.preferIPv4Stack=true
Current Time: 28/02/2024 17:13:34
Host: files.minecraftforge.net [51.79.83.165]
Host: maven.minecraftforge.net [51.79.83.165]
Host: libraries.minecraft.net [13.107.213.31, 13.107.246.31]
Host: launchermeta.mojang.com [13.107.246.31, 13.107.213.31]
Host: piston-meta.mojang.com [13.107.246.31, 13.107.213.31]
java.net.UnknownHostException: authserver.mojang.com: Name or service not known
        at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
        at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:934)
        at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1543)
        at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:852)
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1533)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1385)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1306)
        at net.minecraftforge.installer.DownloadUtils.getIps(DownloadUtils.java:290)
        at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:120)
Exception in thread "main"
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because the return value of "net.minecraftforge.installer.DownloadUtils.getIps(String)" is null
        at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:120)
steven@minecraft01:~/minecraft/atm9nofrills/Server-Files-0.1.8$

**Comment by djnifos** [comment]
https://files.minecraftforge.net/net/minecraftforge/forge/index_1.20.1.html

Go here and download the 47.2.20 "Latest" Installer.  It will match one in your server files, replace the one in your server files with the one you have downloaded, which fixes this problem
